import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.posts.getAll.useQuery();
  const user = useUser();

  console.log(hello.data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {user.isSignedIn ? <SignOutButton /> : <SignIn />}
        <div>
          {hello.data?.map((post) => (
            <div key={post.id}>
              <p>{post.content}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
